name: Feature request
description: Suggest an improvement or new capability
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please describe the problem and the outcome you want.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What are you trying to do? What’s missing today?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see LocalCloud do?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, screenshots, logs, or examples.
    validations:
      required: false
